url: "http://mysite.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
languages: ["en", "el"]
exclude_from_localizations: ["javascript", "images", "css"]
default_locale_in_subfolder: false
