url: "http://mysite.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Despoina Florou Structural Design" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-paginate-v2
languages: ["en", "el"]
exclude_from_localizations: ["javascript", "images", "css"]
default_locale_in_subfolder: false
pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
